---
title: "R Notebook"
output: html_notebook
---

```{r setup}
knitr::opts_knit$set(root.dir = '/Users/charleshanks/desktop/msds/spring_23/ml/FARS2020NationalCSV')
```


```{r}
library(tidyverse)
library(tidytext)
library(caret)
library(fastDummies)
library(randomForest)
```


```{r}
acc = read_csv('accident.csv')  
veh = read_csv('vehicle.csv')
per = read_csv('person.csv')
dru = read_csv('drugs.csv')

```


```{r}
#intersting in the people driving the vehicle that crashed
drivers = per %>% filter(PER_TYP == 1)
```

```{r}
names(acc)
names(drivers)

#finding repeat cols in both datasets
names(drivers) %in% names(acc)

#these cols are not in accidents.csv 
drivers[,5:7]
drivers[,27:126]

distinct_driver_cols = bind_cols(drivers[,5:7],drivers[,27:126])

#this is now the driver ds without distinct features to add to accidents
drivers2 = bind_cols(drivers[,3], distinct_driver_cols)

#dataset now to refine for model
drivers3 = acc %>% left_join(drivers2, by = "ST_CASE")

drivers3 %>% group_by(DRUNK_DR) %>% count()

getwd()
deadly_drivers = write_rds(drivers3)

write_rds(drivers3, file = "/Users/charleshanks/Desktop/MSDS/SPRING_23/ML/FARS_ds")
```

```{r}
#removing the "__NAME" categorical vars" 
drivers3 = drivers3 %>% select(-ends_with('name', ignore.case = TRUE))

drivers3 = drivers3 %>% rename_all(funs(tolower(.)))

#creating class to predict 
drivers3 = drivers3 %>% mutate(class = ifelse(drunk_dr > 0, 1,0)) %>% relocate(class)

#columsn to convert to factor: 
drivers3 = drivers3 %>% select(class, state, st_case, ve_total:persons,county:route,tway_id,rur_urb,func_sys:sp_jur,harm_ev:sch_bus,fatals,str_veh,make:rollover,impact1:air_bag,ejection:extricat,drugs:drug_det,dstatus,hospital:lag_hrs,lag_mins:gvwr_to)

#testing lapply to convert first 3 cols to factor
drivers3[names(drivers3)[1:3]] = lapply(drivers3[names(drivers3)[1:3]], factor)

drivers3 = drivers3 %>% select(-year,-nhs,-tway_id,-milept,-reljct1,-reljct2,-rel_road)

drivers3 = drivers3 %>% select(-body_typ,-mod_year,-tow_veh,-spec_use,-emer_use,-per_typ,-inj_sev,-seat_pos,-hospital,-death_mo,death_yr,-death_hr,-death_mn,-death_tm,-lag_hrs,-lag_mins,-work_inj,-hispanic,-vpicmake,-vpicmodel,-vpicbodyclass,-icfinalbody,-gvwr_from,-gvwr_to)

# do it again!
drivers3[names(drivers3)[40:50]] = lapply(drivers3[names(drivers3)[40:50]], factor)

#drivers3[names(drivers3)[21:38]] = lapply(drivers3[names(drivers3)[21:38]], factor)

#drivers3[names(drivers3)[40:85]] = lapply(drivers3[names(drivers3)[40:85]], factor)

#this is nasty - not best practice for converting these cols, revisit and do this in more clean fashion

drivers3 = drivers3 %>% select(-(death_da:helm_mis))
```


Lot of factors here, this is going to be a lot of dummy cols....
```{r}

drivers3 = drivers3 %>% select(-county)

drivers3 = drivers3 %>% select(-mak_mod)
```
```{r}
d3_cols = names(drivers3) 

drivers4 = drivers3 %>% select(-class) %>% 
  dummy_cols(remove_selected_columns = T) %>% 
     cbind(drivers3 %>% 
          select(class)) %>% 
                relocate(class)
```

Principal Component Analysis: 

```{r}
drivers4[names(drivers4)[18:355]] = lapply(drivers4[names(drivers4)[18:355]], factor)

drivers4 = drivers4 %>% mutate(class = ifelse(class == 1,0,1))

drivers5 = drivers4 %>% select(fatals:age) %>% preProcess(method = c("center", "scale")) %>% predict(drivers4) %>% na.omit()

#income = income %>% select(capital_gain, capital_loss) %>% preProcess(method = c("center", "scale")) %>% predict(income) 

is.infinite(drivers5)
any(sapply(drivers5, function(x) any(is.infinite(x))))

drivers5[names(drivers5[18:355])] = lapply(drivers5[names(drivers5)[18:355]], as.numeric)

pr_driver = prcomp(x = select(drivers5, -class), center = F, scale = F)

summary(pr_driver)

#for some reason cumulative proportion is not displaying in my summary of pca. Here is a workaround: 

vars <- apply(pr_driver$x, 2, var)  
props <- vars / sum(vars)
cumsum(props)
```

```{r}
screeplot(pr_driver, type = "lines")
#something isn't right here.... 

```

